[project]
name = "chapter5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets==3.1.0",
    "gradio>=5.26.0",
    "scikit-learn==1.5.2",
    "torch==2.5.1",
    "transformers==4.46.3",
]
